<?php

namespace Slinpin;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-30 at 20:40:42.
 */
class ConstantTest extends \PHPUnit_Framework_TestCase {
    public static function dataProvider() {
        return array(
            array('a'),
            array('b'),
            array('c'),
            array('d'),
            array('e'),
        );
    }
    
    /**
     * @covers Slinpin\Constant::provide
     * @dataProvider dataProvider
     */
    public function testProvide($value) {
        $expect = $value;
        
        $provider = new Constant($value);

        $actual = $provider->provide();
        
        $this->assertEquals($expect, $actual);
    }
}
