<?php

namespace Slinpin;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-30 at 20:40:42.
 */
class FunctionInvokerTest extends \PHPUnit_Framework_TestCase {
    public static function dataProvider() {
        return array(
            array(function ($a) {return $a;}, array('a'), 'a'),
            array(function ($b) {return $b;}, array('b'), 'b'),
            array(function ($c) {return $c;}, array('c'), 'c'),
            array(function ($d) {return $d;}, array('d'), 'd'),
            array(function ($e) {return $e;}, array('e'), 'e'),
        );
    }
    
    /**
     * @covers Slinpin\FunctionInvoker::invoke
     * @dataProvider dataProvider
     */
    public function testInvoke($method, $values, $value) {
        $expect = $value;
        
        $invoker = new FunctionInvoker($method);

        $actual = $invoker->invoke($values);
        
        $this->assertEquals($expect, $actual);
    }
}
