<?php

namespace Slinpin;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-30 at 20:40:42.
 */
class ScopeTest extends \PHPUnit_Framework_TestCase {
    public static function dataProvider() {
        return array(
            array(array('a'=>'A'), 'a', 'A'),
            array(array('b'=>'B'), 'b', 'B'),
            array(array('c'=>'C'), 'c', 'C'),
            array(array('d'=>'D'), 'd', 'D'),
            array(array('e'=>'E'), 'e', 'E'),
        );
    }
    
    /**
     * @covers Slinpin\Scope::get
     * @dataProvider dataProvider
     */
    public function testGet($values, $key, $value) {
        $expect = $value;
        
        $container = new Scope($values);
        
        $actual = $container->get($key);
        
        $this->assertEquals($expect, $actual);
    }

    /**
     * @covers Slinpin\Scope::set
     * @dataProvider dataProvider
     */
    public function testSet($values, $key, $value) {
        $expect = $value;
        
        $container = new Scope();
        
        $container->set($key, $container->constant($value));
        
        $actual = $container->get($key);
        
        $this->assertEquals($expect, $actual);
    }

    /**
     * @covers Slinpin\Scope::has
     * @dataProvider dataProvider
     */
    public function testHas($values, $key, $value) {
        $container = new Scope($values);
        
        $actual = $container->has($key);
        
        $this->assertTrue($actual);
    }

}
