<?php

namespace Slinpin;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-30 at 20:40:42.
 */
class VariableTest extends \PHPUnit_Framework_TestCase {
    public static function dataProvider() {
        return array(
            array(function () {return 'a';}, 'a'),
            array(function () {return 'b';}, 'b'),
            array(function () {return 'c';}, 'c'),
            array(function () {return 'd';}, 'd'),
            array(function () {return 'e';}, 'e'),
        );
    }
    
    /**
     * @covers Slinpin\Variable::provide
     * @dataProvider dataProvider
     */
    public function testProvide($method, $value) {
        $expect = $value;
        
        $provider = new Variable(new FunctionInvoker($method));

        $actual = $provider->provide();
        
        $this->assertEquals($expect, $actual);
    }
}
